In [1]:
from sklearn.datasets import load_diabetes
diabete = load_diabetes()
X, y = diabete.data, diabete.target

In [2]:
print(X[1])

[-0.00188202 -0.04464164 -0.05147406 -0.02632783 -0.00844872 -0.01916334
  0.07441156 -0.03949338 -0.06832974 -0.09220405]


In [3]:
print(y)

[151.  75. 141. 206. 135.  97. 138.  63. 110. 310. 101.  69. 179. 185.
 118. 171. 166. 144.  97. 168.  68.  49.  68. 245. 184. 202. 137.  85.
 131. 283. 129.  59. 341.  87.  65. 102. 265. 276. 252.  90. 100.  55.
  61.  92. 259.  53. 190. 142.  75. 142. 155. 225.  59. 104. 182. 128.
  52.  37. 170. 170.  61. 144.  52. 128.  71. 163. 150.  97. 160. 178.
  48. 270. 202. 111.  85.  42. 170. 200. 252. 113. 143.  51.  52. 210.
  65. 141.  55. 134.  42. 111.  98. 164.  48.  96.  90. 162. 150. 279.
  92.  83. 128. 102. 302. 198.  95.  53. 134. 144. 232.  81. 104.  59.
 246. 297. 258. 229. 275. 281. 179. 200. 200. 173. 180.  84. 121. 161.
  99. 109. 115. 268. 274. 158. 107.  83. 103. 272.  85. 280. 336. 281.
 118. 317. 235.  60. 174. 259. 178. 128.  96. 126. 288.  88. 292.  71.
 197. 186.  25.  84.  96. 195.  53. 217. 172. 131. 214.  59.  70. 220.
 268. 152.  47.  74. 295. 101. 151. 127. 237. 225.  81. 151. 107.  64.
 138. 185. 265. 101. 137. 143. 141.  79. 292. 178.  91. 116.  86. 122.
  72. 

In [4]:
results = {}

In [5]:
diabete.data.shape

(442, 10)

In [6]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
import numpy as np

# DecisionTreeClassifier

In [7]:
from sklearn.tree import DecisionTreeRegressor
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [8]:
clf_tree = DecisionTreeRegressor(criterion='mse',random_state=0) 

In [9]:
clf_tree.fit(X, y)
param_grid = {'criterion':['mse', 'mae'], 'max_depth':[3, 7, 9]}
clf_tree = GridSearchCV(clf_tree, param_grid,cv=3)

In [10]:
clf_tree.fit(X_train, y_train)


GridSearchCV(cv=3, estimator=DecisionTreeRegressor(random_state=0),
             param_grid={'criterion': ['mse', 'mae'], 'max_depth': [3, 7, 9]})

In [11]:
scores = cross_val_score(clf_tree, X, y,cv=3)
scores

array([0.36454067, 0.3736033 , 0.33827764])

In [12]:
results["tree"] = np.mean(scores)

In [13]:
clf_tree.predict([[2., 2., 3., 3.,2., 2., 3., 3.,2., 2.]])

array([263.22857143])

# KNN

In [14]:
from sklearn.neighbors import KNeighborsRegressor

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
param_grid = {'n_neighbors':[1, 3, 5, 7], 'p':[1, 2]}
clf_knn = KNeighborsRegressor()
clf_knn.fit(X, y)


KNeighborsRegressor()

In [15]:
clf_knn = GridSearchCV(clf_knn, param_grid, cv=3)
clf_knn.fit(X_train, y_train)

GridSearchCV(cv=3, estimator=KNeighborsRegressor(),
             param_grid={'n_neighbors': [1, 3, 5, 7], 'p': [1, 2]})

In [16]:
scores = cross_val_score(clf_knn, X, y, cv=3)
scores

array([0.35402976, 0.39515022, 0.47126723])

In [17]:
clf_knn.best_params_

{'n_neighbors': 7, 'p': 2}

In [18]:
results["knn"] = np.mean(scores)

In [19]:
clf_knn.predict([[2., 2., 3., 3.,2., 2., 3., 3.,2., 2.]])

array([235.14285714])

# GaussianNB

In [20]:
from sklearn.naive_bayes import GaussianNB

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

clf_nb = GaussianNB()
clf_nb.fit(X_train, y_train)

scores = cross_val_score(clf_nb, X, y, cv=3)
scores

D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


array([0.00675676, 0.01360544, 0.00680272])

In [21]:
results["nb"] = np.mean(scores)

In [22]:
clf_nb.predict([[2., 2., 3., 3.,2., 2., 3., 3.,2., 2.]])

array([142.])

# SVR

In [23]:
from sklearn.svm import SVR


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

param_grid = {'kernel':['linear', 'poly', 'rbf', 'sigmoid'], 'C':[1, 3, 7], 'epsilon':[0.1, 0.2]}
clf_svr = SVR()
clf_svr.fit(X, y)
clf_svr = GridSearchCV(clf_svr, param_grid, scoring= 'r2', cv=3)
clf_svr.fit(X_train, y_train)


scores = cross_val_score(clf_svr, X, y, scoring= 'r2', cv=3)
scores

array([0.44862293, 0.48139306, 0.52133906])

In [24]:
results["svm"] = np.mean(scores)
results["svm"]

0.48378501475332863

In [25]:
clf_svr.predict([[2., 2., 3., 3.,2., 2., 3., 3.,2., 2.]])

array([376.27638459])

# RNA

In [26]:
from sklearn.neural_network import MLPClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
clf_mlp = MLPClassifier(hidden_layer_sizes=[50, 30, 10], max_iter=9000, random_state=0)
clf_mlp.fit(X_train, y_train)

scores = cross_val_score(clf_mlp, X, y, cv=3, scoring='r2')
scores

D:\Anaconda\lib\site-packages\sklearn\model_selection\_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(("The least populated class in y has only %d"


array([ 0.11300242, -0.0365885 , -0.0440974 ])

In [27]:
results["mlp"] = np.mean(scores)

In [28]:
clf_mlp.predict([[2., 2., 3., 3.,2., 2., 3., 3.,2., 2.]])

array([230.])

In [29]:
for key, value in results.items():
    print(key, value)

tree 0.35880719943380274
knn 0.40681573456538517
nb 0.009054973340687627
svm 0.48378501475332863
mlp 0.010772175722745359
