# digits

In [1]:
from sklearn.datasets import load_digits
digits = load_digits()
X, y = digits.data, digits.target

In [2]:
print(X[1])

[ 0.  0.  0. 12. 13.  5.  0.  0.  0.  0.  0. 11. 16.  9.  0.  0.  0.  0.
  3. 15. 16.  6.  0.  0.  0.  7. 15. 16. 16.  2.  0.  0.  0.  0.  1. 16.
 16.  3.  0.  0.  0.  0.  1. 16. 16.  6.  0.  0.  0.  0.  1. 16. 16.  6.
  0.  0.  0.  0.  0. 11. 16. 10.  0.  0.]


In [3]:
print(y)

[0 1 2 ... 8 9 8]


In [4]:
results = {}

In [5]:
digits.data.shape

(1797, 64)

In [6]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
import numpy as np

# DecisionTreeClassifier

In [7]:
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

param_grid = {'criterion':['gini','entropy'], 'max_depth':[3, 7, 9]}
clf_tree = DecisionTreeClassifier(random_state=0)
clf_tree.fit(X, y)
clf_tree = GridSearchCV(clf_tree, param_grid, scoring=('f1_weighted'), cv=3)
clf_tree.fit(X_train, y_train)


scores = cross_val_score(clf_tree, X, y, cv=3, scoring='f1_weighted')
scores

array([0.74466726, 0.77501298, 0.75204535])

In [8]:
results["tree"] = np.mean(scores)

In [9]:
clf_tree.predict([[2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.]])

array([7])

# k-NN

In [10]:
from sklearn.neighbors import KNeighborsClassifier


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

param_grid = {'n_neighbors':[1, 3, 5, 7], 'p':[1, 2]}
clf_knn = KNeighborsClassifier()
clf_knn.fit(X, y)
clf_knn = GridSearchCV(clf_knn, param_grid, scoring=('f1_weighted'), cv=3)
clf_knn.fit(X_train, y_train)

scores = cross_val_score(clf_knn, X, y, cv=3, scoring='f1_weighted')
scores

array([0.95680465, 0.96991908, 0.9647774 ])

In [11]:
results["knn"] = np.mean(scores)

In [12]:
clf_knn.predict([[2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.]])

array([0])

# GaussianNB

In [13]:
from sklearn.naive_bayes import GaussianNB

clf_nb = GaussianNB()
clf_nb.fit(X, y)

scores = cross_val_score(clf_nb, X, y, cv=3, scoring='f1_weighted')
scores

array([0.82409571, 0.80427195, 0.81918411])

In [14]:
results["nb"] = np.mean(scores)

In [15]:
clf_nb.predict([[2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.]])

array([9])

# SVC

In [16]:
from sklearn.svm import SVC


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

param_grid = {'kernel':['linear', 'poly', 'rbf', 'sigmoid'], 'C':[1, 3, 7]
}
clf_svc = SVC()
clf_svc.fit(X, y)
clf_svc = GridSearchCV(clf_svc, param_grid, scoring=('f1_weighted'), cv=3)
clf_svc.fit(X_train, y_train)


scores = cross_val_score(clf_svc, X, y, cv=3, scoring='f1_weighted')
scores

array([0.96838199, 0.98169909, 0.97497357])

In [17]:
results["svm"] = np.mean(scores)

In [18]:
clf_svc.predict([[2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.]])

array([4])

# RNA

In [19]:
from sklearn.neural_network import MLPClassifier

clf_mlp = MLPClassifier(hidden_layer_sizes=(50, 30, 10), max_iter=5000, random_state=0)
clf_mlp.fit(X, y)

scores = cross_val_score(clf_mlp, X, y, cv=3, scoring='f1_weighted')
scores

array([0.92218953, 0.91016275, 0.89276324])

In [20]:
results["mlp"] = np.mean(scores)

In [21]:
clf_mlp.predict([[2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.,2., 2., 3., 3.]])

array([4])

In [22]:
for key, value in results.items():
    print(key, value)

tree 0.7572418632025579
knn 0.9638337100004549
nb 0.8158505897021469
svm 0.9750182155092152
mlp 0.9083718417581751
